# Generated by Django 3.2.9 on 2021-12-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_commerical_properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.singlecommericalunit'),
        ),
        migrations.AddField(
            model_name='user',
            name='related_residential_properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.singleresidentialunit'),
        ),
    ]
