# Generated by Django 3.2.9 on 2022-01-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('photos', models.ImageField(null=True, upload_to='')),
                ('property_type', models.CharField(choices=[('O', 'Officetel'), ('A', 'Apartment'), ('C', 'Commerical')], default='A', max_length=1)),
                ('number_of_floors', models.IntegerField()),
                ('number_of_rentals', models.IntegerField()),
                ('landlord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='SingleRentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rental', models.FloatField()),
                ('floor', models.IntegerField()),
                ('business_type', models.CharField(max_length=30)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
    ]
