# Generated by Django 3.2.9 on 2021-12-19 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('photos', models.ImageField(upload_to='')),
                ('property_type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commerical')], default='R', max_length=1)),
                ('floors', models.IntegerField()),
                ('underground', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('photos', models.ImageField(upload_to='')),
                ('property_type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commerical')], default='R', max_length=1)),
                ('number_of_rentals', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleResidentialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rental', models.FloatField()),
                ('residential_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.residential')),
            ],
        ),
        migrations.CreateModel(
            name='SingleCommericalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('business_type', models.CharField(max_length=30)),
                ('monthly_rental', models.FloatField()),
                ('commerical_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.commerical')),
            ],
        ),
    ]
