# Generated by Django 3.2.9 on 2022-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_singlerentalunit_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Changwon Building', max_length=100),
            preserve_default=False,
        ),
    ]
