# Generated by Django 3.2.9 on 2021-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlecommericalunit',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
