# Generated by Django 3.2.9 on 2022-01-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
