# Generated by Django 3.2.9 on 2021-12-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_singlecommericalunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecommericalunit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
