# Generated by Django 3.2.9 on 2022-01-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
