# Generated by Django 3.2.9 on 2022-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlerentalunit',
            name='monthly_rental',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
