# Generated by Django 3.2.8 on 2021-11-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeycomb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of user'),
        ),
    ]
